export const VOLUNTEER_REGISTER_REQUEST = 'VOLUNTEER_REGISTER_REQUEST';
export const VOLUNTEER_REGISTER_SUCCESS = 'VOLUNTEER_REGISTER_SUCCESS';
export const VOLUNTEER_REGISTER_FAIL = 'VOLUNTEER_REGISTER_FAIL';
